name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run: |
        - ssh -t ubuntu@52.90.58.254 "mkdir test"
        - echo "file sync"
        - echo "dipak new code"
