name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run: |
        - aws rsync -zhrv ./* ubuntu@52.90.58.254:/home/ubuntu/
        - echo "file sync"
        - echo "dipak new code"