name: Upload Website
on:
  push:
    branches:
      - "main"    
jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: dkd 
        run: | 
          echo "Ddd"
          ssh -t ubuntu@52.90.58.254 "git clone ''" 
  #        rsync -zhvr . ubuntu@52.90.58.254:/home/ubuntu/dipak/
