name: Upload Website

on:
  push:
    branches:
      - main
    

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Demo
    - uses: actions/checkout@main
      run: |
        - echo "ddfsds"
      