name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run:
       ls
       - rsync -zhvr . ubuntu@552.90.58.254:/home/ubuntu/dipak/
    
