name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run: |
      
        - touch index.html
        - echo "file created"
        - rsync -zhvr ./index.html ubuntu@52.90.58.254:/home/ubuntu/dipak/
        - echo "file sync"
        - echo "dipak new code"